### ISSUE TITLE
Gefundene Probleme

### ISSUE THREAD

**Issue by MorMundHS-MA** [int-lecture/repo-05#1]
* Wenn das Datum in einer /send Anfrage falsch ist, bekommt man einen Internal Server Error. Sollte ein 4** error wegen falschen Formats sein
* Wenn man einen Parameter in einer /send Anfrage weg lässt wird die Anfrage trotzdem akzeptiert.

**Comment by incognito17** [comment]
Sollte jetzt funktionieren.

(Mit Rest-Client geht es)

**Comment by incognito17** [comment]
Müssen noch auf den Server hochladen

**Comment by incognito17** [comment]
Sollte jetzt laufen.

MfG
