### ISSUE TITLE
Verschiedene Versionen über Verzeichnisse

### ISSUE THREAD

**Issue by thomsmits** [int-lecture/repo-05#4]
git ist ein Versionsverwaltungssystem. Man bildet verschiedene Versionen einfach durch aufeinanderfolgende Commits oder durch Branches ab. Die Verwendung von Verzeichnissen entspricht nicht dieser Idee.

**Comment by incognito17** [comment]
Die Verzeichnise mit den verschiedenen Versionen haben wir nur für unsere Homepage verwendet - die Repository ist nun mehr aufgeräumt.
